/*
  Copy this file into config/tracker-config.js after duplicating the repo for
  the project management team.
*/
window.TRACKER_CONFIG = {
  documentTitle: "Project Management Weekly Tracker",
  storageNamespace: "project-management-weekly-tracker",

  labels: {
    sidebarEyebrow: "Leadership Operations",
    sidebarTitle: "Project Management Tracker",
    weekLabel: "Week",
    sourceLabel: "Source",
    workstreamsTitle: "Workstreams",
    statusTitle: "Status Mix",
    topbarEyebrow: "Weekly Portfolio Review",
    topbarTitle: "Project management portfolio overview",
    briefButton: "Leadership Brief",
    exportButton: "Export CSV",
    addButton: "Add Update",
    attentionEyebrow: "Leadership",
    attentionTitle: "Attention Queue",
    searchLabel: "Search",
    searchPlaceholder: "Project, owner, workstream, risk",
    workstreamFilterLabel: "Workstream",
    statusFilterLabel: "Status",
    leadershipOnlyLabel: "Leadership only",
    dialogEyebrow: "Weekly Intake",
    dialogTitle: "New project update",
    projectLabel: "Project",
    projectPlaceholder: "Portfolio rollout - stakeholder readiness",
    ownerLabel: "Owner",
    ownerPlaceholder: "Project lead",
    targetDateLabel: "Target date",
    targetDatePlaceholder: "5/15",
    updateLabel: "This week update",
    updatePlaceholder: "What changed this week?",
    impactLabel: "Business impact",
    impactPlaceholder: "Why it matters for leadership",
    riskLabel: "Blocker or risk",
    riskPlaceholder: "Dependency, decision, access issue, or timeline risk",
    askLabel: "Leadership ask",
    jiraLabel: "Jira key or epic",
    jiraPlaceholder: "PMO-123",
    helpLabel: "Help needed",
    helpPlaceholder: "Decision, escalation, owner alignment",
    cancelButton: "Cancel",
    saveButton: "Save update",
  },

  views: {
    projects: { nav: "Projects", eyebrow: "Portfolio", title: "Projects" },
    highlights: { nav: "Highlights", eyebrow: "Business", title: "Highlights" },
    metrics: { nav: "Metrics", eyebrow: "Operations", title: "Metrics" },
    jira: { nav: "Jira", eyebrow: "Delivery", title: "Jira" },
  },

  statuses: ["Completed", "On Track", "Monitoring", "At Risk", "Blocked", "Upcoming"],
  askOptions: ["No", "Yes", "Review"],
  completedStatuses: ["Completed"],
  onTrackStatuses: ["On Track"],
  attentionStatuses: ["Blocked", "At Risk", "Monitoring"],
  severityScores: {
    Blocked: 5,
    "At Risk": 4,
    Monitoring: 3,
    "On Track": 2,
    Upcoming: 1,
    Completed: 0,
  },
  statusTones: {
    Completed: "completed",
    "On Track": "ontrack",
    Monitoring: "monitoring",
    "At Risk": "risk",
    Blocked: "blocked",
    Upcoming: "upcoming",
  },

  defaultWorkstreams: [
    "Intake",
    "Planning",
    "Delivery",
    "Change Management",
    "Reporting",
    "Governance",
  ],
  defaultWorkstream: "Delivery",

  metricCards: {
    projectsLabel: "Projects",
    projectsNote: "{onTrack} on track",
    attentionLabel: "Leadership asks",
    attentionNote: "active attention",
    completedLabel: "Completed",
    completedNote: "closed updates",
    highlightsLabel: "Business highlights",
    highlightsNote: "{metrics} metrics",
  },

  theme: {
    slate: "#829cb2",
    black: "#000000",
    bg: "#d2d2d2",
    surface: "#ffffff",
    surfaceMuted: "#f4f4f4",
    text: "#000000",
    muted: "#414141",
    subtle: "#636363",
    line: "#c7c7c7",
    lineSoft: "#e1e1e1",
    accent: "#829cb2",
    accentDeep: "#000000",
    accentSoft: "#edf2f5",
    success: "#2f7d4f",
    successSoft: "#e7f1eb",
    warning: "#c87b12",
    warningSoft: "#f7ecd9",
    danger: "#b84c43",
    dangerSoft: "#f7e6e4",
  },
};
