/*
  Copy this file into config/tracker-config.js after duplicating the repo for
  the project management team.
*/
window.TRACKER_CONFIG = {
  documentTitle: "Project Management Weekly Tracker",
  storageNamespace: "project-management-weekly-tracker",

  labels: {
    sidebarEyebrow: "Leadership Operations",
    sidebarTitle: "Project Management Tracker",
    weekLabel: "Week",
    sourceLabel: "Source",
    workstreamsTitle: "Workstreams",
    statusTitle: "Status Mix",
    topbarEyebrow: "Weekly Portfolio Review",
    topbarTitle: "Project management portfolio overview",
    briefButton: "Leadership Brief",
    exportButton: "Export CSV",
    addButton: "Add Update",
    attentionEyebrow: "Leadership",
    attentionTitle: "Attention Queue",
    searchLabel: "Search",
    searchPlaceholder: "Project, owner, workstream, risk",
    workstreamFilterLabel: "Workstream",
    statusFilterLabel: "Status",
    leadershipOnlyLabel: "Leadership only",
    dialogEyebrow: "Weekly Intake",
    dialogTitle: "New project update",
    projectLabel: "Project",
    projectPlaceholder: "Portfolio rollout - stakeholder readiness",
    ownerLabel: "Owner",
    ownerPlaceholder: "Project lead",
    targetDateLabel: "Target date",
    targetDatePlaceholder: "5/15",
    updateLabel: "This week update",
    updatePlaceholder: "What changed this week?",
    impactLabel: "Business impact",
    impactPlaceholder: "Why it matters for leadership",
    riskLabel: "Blocker or risk",
    riskPlaceholder: "Dependency, decision, access issue, or timeline risk",
    askLabel: "Leadership ask",
    jiraLabel: "Jira key or epic",
    jiraPlaceholder: "PMO-123",
    helpLabel: "Help needed",
    helpPlaceholder: "Decision, escalation, owner alignment",
    cancelButton: "Cancel",
    saveButton: "Save update",
  },

  views: {
    projects: { nav: "Projects", eyebrow: "Portfolio", title: "Projects" },
    highlights: { nav: "Highlights", eyebrow: "Business", title: "Highlights" },
    metrics: { nav: "Metrics", eyebrow: "Operations", title: "Metrics" },
    jira: { nav: "Jira", eyebrow: "Delivery", title: "Jira" },
  },

  statuses: ["Completed", "On Track", "Monitoring", "At Risk", "Blocked", "Upcoming"],
  askOptions: ["No", "Yes", "Review"],
  completedStatuses: ["Completed"],
  onTrackStatuses: ["On Track"],
  attentionStatuses: ["Blocked", "At Risk", "Monitoring"],
  severityScores: {
    Blocked: 5,
    "At Risk": 4,
    Monitoring: 3,
    "On Track": 2,
    Upcoming: 1,
    Completed: 0,
  },
  statusTones: {
    Completed: "completed",
    "On Track": "ontrack",
    Monitoring: "monitoring",
    "At Risk": "risk",
    Blocked: "blocked",
    Upcoming: "upcoming",
  },

  defaultWorkstreams: [
    "Intake",
    "Planning",
    "Delivery",
    "Change Management",
    "Reporting",
    "Governance",
  ],
  defaultWorkstream: "Delivery",

  metricCards: {
    projectsLabel: "Projects",
    projectsNote: "{onTrack} on track",
    attentionLabel: "Leadership asks",
    attentionNote: "active attention",
    completedLabel: "Completed",
    completedNote: "closed updates",
    highlightsLabel: "Business highlights",
    highlightsNote: "{metrics} metrics",
  },

  theme: {
    bg: "#f6f8fb",
    surface: "#ffffff",
    surfaceMuted: "#f9fafc",
    text: "#172033",
    muted: "#657184",
    subtle: "#8a95a5",
    line: "#d9e1eb",
    lineSoft: "#e8edf3",
    accent: "#2f6f9f",
    accentDeep: "#214f73",
    accentSoft: "#eaf3f8",
    success: "#1f7a5f",
    successSoft: "#e8f4ef",
    warning: "#94640c",
    warningSoft: "#f7efe1",
    danger: "#b03a48",
    dangerSoft: "#f8e9ec",
  },
};
